# File
sonar_path: examples/Sonar_2023-09-12_09.04.57.sl2
save_path: outputs

# Use <filename>.sl2 as project name
filename_as_project_name: True

# If false above, use this name instead
project_name: Sonar 

# Delete previous project outputs
# Default for now.
#overwrite_project: True 

# TODO: Enable saving of ping data to csv
save_csv: True

# TODO: Add additional csv file to save all channels into one
save_csv_all: True

# TODO: Position corrections (meters)
transducer_x_offset: 0,0
transducer_y_offset: 0,0


# TODO:
# Export points shapefile?

# Sonar intensity corrections
egn: True
egn_stretch: 2 # None, 1) min-max, 2) percent clip
egn_stretch_factor_min: 10 # for percent clip only
egn_stretch_factor_max: 90 # for percent clip only

# Sonogram images
water_column_present: True
water_column_removed: True
sonogram_img_format: png # Todo

# Speed corrected sonogram exports
export_speed_corrected: True
speed_correction: False

# Depth detection and shadow removal
remove_shadows: 0 # 0-false, 1-removeall shadows, 2-remove only bank shadows
depth_detection_method: 0 # 0-sensor, 1-zheng et al. 2=thresholding
smooth_depth: True # 0-false, 1-true
adjust_depth: 0 # in meters, positive=increase, 
plot_bedpicks: 0 # 0-false, 1-true, hmm ano to?

# Exports
resolution: .2 # Meter per pixel
export_georef_sidescan: gtiff # false, gtiff, png
export_sidescan_substrates_map: True # false, gtiff, png, shapefile?

# georeferenced sidescan
sidescan_wcp: True
sidescan_wcr: True
colormap: hotdog

# Substrate mapping
map_substrate: False
subtrate_plots: false
substrate_raster: False
substrate_polygon: False
classification_method: max